# Generated by Django 2.2 on 2019-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Please add details about your event here', null=True)),
                ('start_time', models.DateTimeField(null=True, verbose_name='start time and date')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end time and date')),
                ('event_image', models.ImageField(null=True, upload_to='images/')),
                ('category', models.ManyToManyField(help_text='Select a category for this event', to='eventFinderApp.Category')),
            ],
        ),
    ]
