# Generated by Django 2.2 on 2019-11-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('short_description', models.CharField(default='Description', max_length=100)),
                ('description', models.TextField(help_text='Please add details about your event here', null=True)),
                ('start_time', models.DateTimeField(null=True, verbose_name='start time and date')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end time and date')),
                ('event_image', models.ImageField(null=True, upload_to='images/')),
                ('category', models.ManyToManyField(help_text='Select a category for this event', to='eventFinderApp.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.CustomUser')),
            ],
        ),
    ]
