# Generated by Django 2.2 on 2019-09-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventFinderApp.Event'),
        ),
    ]
