# Generated by Django 2.2 on 2019-09-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_category_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventFinderApp.Category'),
        ),
    ]
