# Generated by Django 2.2 on 2019-09-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0004_auto_20190906_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
    ]
