# Generated by Django 2.2 on 2019-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0006_auto_20190906_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='eventFinderApp.Category'),
        ),
    ]
