# Generated by Django 2.2 on 2019-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0007_auto_20190906_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this event', to='eventFinderApp.Category'),
        ),
    ]
