# Generated by Django 2.2 on 2019-09-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0013_auto_20190911_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
