# Generated by Django 2.2 on 2019-09-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0014_auto_20190911_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
